#ifndef GF_COMMON_H
#define GF_COMMON_H

#define GF_DEFAULT_WINDOW_HEIGHT 600
#define GF_DEFAULT_WINDOW_WIDTH  800

#define GF_ATTRIB_VERT_LOCATION 0

#define GF_UNIFORM_PROJECTION_MAT_LOCATION 0

#endif
